version: '3.2'

services:
    database:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
            - '6603:3306'
        environment:
            MYSQL_ROOT_PASSWORD: HEY #${MYSQL_ROOT_PASS}
        networks: 
            backend:
                # ipv4_address: 172.16.100.2


    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        network_mode: host
        environment:
            PMA_HOST: database
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: HEY #${MYSQL_ROOT_PASS}
        volumes: 
            - ./shared:/app
        ports:
            - '8080:80'
        networks: 
            backend:
networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: 172.16.100.0/24