version: '3'

services:

    # mysql service
    mysql_db:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_DATABASE: ${MYSQL_DB_NAME}
            MYSQL_USER: ${MYSQL_DB_USER}
            MYSQL_PASSWORD: ${MYSQL_PASS}
        ports:
            - "6033:6033"
        volumes:
            - dbdata:/var/lib/mysql

    # phpmyadmin service
    phpmyadmin:
        image: phpmyadmin:${PHPMYADMIN_VERSION}
        container_name: phpmyadmin_app
        links:
            - mysql_db
        environment:
            PMA_HOST: mysql_db
            PMA_PORT: 6033
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:8080

volumes:    
    dbdata: